### ISSUE TITLE
Error when using Splat 5.0.2

### ISSUE THREAD

**Issue by reyntjesr** [joelweiss/Splat.Serilog#1]
Hi Joel,

I came across this error when I updated Splat from version 4.0.2 to 5.0.2

Method 'get_IsDebugEnabled' in type 'Splat.Serilog.SerilogLogger' from assembly 'Splat.Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Maybe (hopefully a small) update is needed in your code?

with kind regards,
  Robert

**Comment by joelweiss** [comment]
Sorry, I didn't notice this issue.

This should be fixed with #2
