### ISSUE TITLE
question: Would you consider allowing Splat to take ownership of Splat.Serilog?

### ISSUE THREAD

**Issue by RLittlesII** [joelweiss/Splat.Serilog#3]
We are currently trying to do some improvement work on Splat.  This includes interoperability with DI and logging frameworks.  Would you consider allowing Splat to take ownership of this library so we can handle maintenance and support going forward?

Relates to: https://github.com/reactiveui/splat/issues/232

**Comment by joelweiss** [comment]
@RLittlesII What would that entail?

**Comment by glennawatson** [comment]
@joelweiss becoming co-owner with reactiveui on the nuget package. We can port the package over and give full acknowledge of your contribution of this package.

**Comment by joelweiss** [comment]
What about the code base?

**Comment by glennawatson** [comment]
It would become integrated into the main splat repository. You can keep this repo open also. 

We are taking over the nlog and log4net projects also (the guy behind those is doing the conversion work directly for us)

**Comment by joelweiss** [comment]
I am in.

**Comment by glennawatson** [comment]
Hey Joel,

Added a PR here https://github.com/reactiveui/splat/pull/252 -- given you full attribution for providing the work until now.

**Comment by joelweiss** [comment]
Leaving this issue open to add an update to the documentation forwarding to the new repo and api
